const API=localStorage.getItem("souqna_api")||"http://localhost:3000/api";
const token=()=>localStorage.getItem("souqna_token");
const req=async(path,opt={})=>{opt.headers={...(opt.headers||{}),...(token()?{Authorization:"Bearer "+token()}:{})};if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)}let r=await fetch(API+path,opt);if(!r.ok)throw new Error((await r.json()).error||"خطا");return r.json()};
async function home(){let [cats,ads]=await Promise.all([req("/categories"),req("/ads")]);document.getElementById("app").innerHTML=`<div class="wrap"><header class="top"><div class="brand">🛍️ سوقنا</div></header><section class="hero"><h1>أهلاً بك في سوقنا 👋</h1><p class="muted">اشترِ وبِع كل شيء بسهولة</p><div class="search"><input id="q" placeholder="ابحث عن سيارة، عقار، جوال..." oninput="doSearch()"></div></section><h2 style="padding:0 20px">التصنيفات</h2><section class="cats">${cats.map(c=>`<button class="cat" onclick="filter('${c.slug}')">${c.icon||"📦"}<br>${c.name}</button>`).join("")}</section><h2 style="padding:20px 20px 0">أحدث الإعلانات</h2><section id="ads" class="grid">${ads.map(card).join("")}</section><div class="nav"><button class="btn" onclick="addAd()">+ إضافة إعلان</button> <button onclick="login()">دخول</button> <button onclick="admin()">الإدارة</button></div></div>`}
function card(a){return `<article class="card"><div class="pic">📦</div><div class="body"><b>${a.title}</b><div class="price">${Number(a.price||0).toLocaleString("ar-SA")} ريال</div><div class="muted">📍 ${a.city||"السعودية"} · ${a.category_name||""}</div></div></article>`}
async function doSearch(){let q=document.getElementById("q").value;let d=await req("/ads?q="+encodeURIComponent(q));document.getElementById("ads").innerHTML=d.map(card).join("")}
async function filter(c){let d=await req("/ads?category="+c);document.getElementById("ads").innerHTML=d.map(card).join("")}
function login(){document.getElementById("app").innerHTML=`<div class="page"><div class="panel"><h2>تسجيل الدخول</h2><form class="form" onsubmit="auth(event)"><input id="email" type="email" placeholder="البريد الإلكتروني" required><input id="password" type="password" placeholder="كلمة المرور" required><button class="btn">دخول</button></form><p class="muted">للتسجيل، استخدم API أو أضف شاشة التسجيل الكاملة.</p></div></div>`}
async function auth(e){e.preventDefault();try{let x=await req("/auth/login",{method:"POST",body:{email:email.value,password:password.value}});localStorage.setItem("souqna_token",x.token);home()}catch(x){alert(x.message)}}
function addAd(){if(!token()){alert("يرجى تسجيل الدخول أولاً");return}document.getElementById("app").innerHTML=`<div class="page"><div class="panel"><h2>إضافة إعلان</h2><form class="form" onsubmit="publish(event)"><input id="title" placeholder="عنوان الإعلان" required><input id="category_id" placeholder="معرّف التصنيف UUID" required><input id="price" type="number" placeholder="السعر"><input id="city" placeholder="المدينة"><textarea id="description" placeholder="الوصف"></textarea><button class="btn">نشر</button></form></div></div>`}
async function publish(e){e.preventDefault();try{await req("/ads",{method:"POST",body:{title:title.value,category_id:category_id.value,price:price.value,city:city.value,description:description.value}});alert("تم إرسال الإعلان للمراجعة");home()}catch(x){alert(x.message)}}
function admin(){document.getElementById("app").innerHTML=`<div class="page"><div class="panel"><h2>لوحة الإدارة</h2><p class="muted">تتطلب حساب admin. استخدم API: GET /api/admin/ads و PATCH /api/admin/ads/:id</p></div></div>`}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");home();